# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(365, 331)
        self.Mode = QtWidgets.QComboBox(parent=Dialog)
        self.Mode.setGeometry(QtCore.QRect(210, 40, 141, 22))
        self.Mode.setObjectName("Mode")
        self.Start = QtWidgets.QPushButton(parent=Dialog)
        self.Start.setGeometry(QtCore.QRect(20, 40, 171, 21))
        self.Start.setObjectName("Start")
        self.A11 = QtWidgets.QPushButton(parent=Dialog)
        self.A11.setGeometry(QtCore.QRect(20, 80, 51, 51))
        self.A11.setObjectName("A11")
        self.A12 = QtWidgets.QPushButton(parent=Dialog)
        self.A12.setGeometry(QtCore.QRect(80, 80, 51, 51))
        self.A12.setObjectName("A12")
        self.A13 = QtWidgets.QPushButton(parent=Dialog)
        self.A13.setGeometry(QtCore.QRect(140, 80, 51, 51))
        self.A13.setObjectName("A13")
        self.A21 = QtWidgets.QPushButton(parent=Dialog)
        self.A21.setGeometry(QtCore.QRect(20, 140, 51, 51))
        self.A21.setObjectName("A21")
        self.A22 = QtWidgets.QPushButton(parent=Dialog)
        self.A22.setGeometry(QtCore.QRect(80, 140, 51, 51))
        self.A22.setObjectName("A22")
        self.A23 = QtWidgets.QPushButton(parent=Dialog)
        self.A23.setGeometry(QtCore.QRect(140, 140, 51, 51))
        self.A23.setObjectName("A23")
        self.A31 = QtWidgets.QPushButton(parent=Dialog)
        self.A31.setGeometry(QtCore.QRect(20, 200, 51, 51))
        self.A31.setObjectName("A31")
        self.A32 = QtWidgets.QPushButton(parent=Dialog)
        self.A32.setGeometry(QtCore.QRect(80, 200, 51, 51))
        self.A32.setObjectName("A32")
        self.A33 = QtWidgets.QPushButton(parent=Dialog)
        self.A33.setGeometry(QtCore.QRect(140, 200, 51, 51))
        self.A33.setObjectName("A33")
        self.Win = QtWidgets.QLabel(parent=Dialog)
        self.Win.setGeometry(QtCore.QRect(20, 280, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Win.setFont(font)
        self.Win.setObjectName("Win")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Start.setText(_translate("Dialog", "PushButton"))
        self.A11.setText(_translate("Dialog", "PushButton"))
        self.A12.setText(_translate("Dialog", "PushButton"))
        self.A13.setText(_translate("Dialog", "PushButton"))
        self.A21.setText(_translate("Dialog", "PushButton"))
        self.A22.setText(_translate("Dialog", "PushButton"))
        self.A23.setText(_translate("Dialog", "PushButton"))
        self.A31.setText(_translate("Dialog", "PushButton"))
        self.A32.setText(_translate("Dialog", "PushButton"))
        self.A33.setText(_translate("Dialog", "PushButton"))
        self.Win.setText(_translate("Dialog", "TextLabel"))
